### ISSUE TITLE
Type 'Expression' not implemented: 'class'

### ISSUE THREAD

**Issue by ichordev** [MrcSnm/D-Metal-Binding#2]
Compiling on macOS ARM64 with LDC 1.32.0 yields this error:
`d-metal-binding/source/objc/runtime.d(10,12): Error: Internal compiler error: Type 'Expression' not implemented: 'class'`
Possibly a compiler bug?

**Comment by MrcSnm** [comment]
Not a compiler bug :D

Actually, `extern(Objective-C)`is only implemented in DMD. I was planning to implement everything first and after that I would try to check if I can copy-paste some of DMD code into LDC

**Comment by MrcSnm** [comment]
That is a pretty showstopper thing since DMD doesn't support iOS compilation and LDC doesn't support `extern(Objective-C)`. I hope that having more stuff being done on Mac could help a little bit the interest of LDC into implementing or even helping me implement that

**Comment by ichordev** [comment]
I had no idea. Cross-arch ObjC bindings are really important! 😬 I hope that'll be resolved soon...
